# -*- coding: utf-8 -*-
"""APP SPP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1D2tC3zyyyeNkreZAtBAnG2-zedwPKw
"""

import streamlit
import pandas as pd
import re
import difflib
from datetime import datetime
import string
import io
from xlsxwriter import Workbook

# -------------------------
# Helper dan konfigurasi
# -------------------------

STOPWORDS = {
    "bulan","ini","juga","ya","assalamualaikum","ustadz","pak","ibu","saya",
    "untuk","atas","nama","anak","santri","bayar","pembayaran","rp","ribu","rb",
    "sebesar","berapa","dengan","yg","telah","sudah","kpd","ke","di","dan",
    "jadi","pakai","uang","sako","saku", "SPO", "uang saki", "ananda",
    # Tambahkan nama-nama bulan sebagai stopwords agar tidak terdeteksi sebagai nama santri
    "januari", "februari", "maret", "april", "mei", "juni", "juli", "agustus",
    "september", "oktober", "november", "desember"
}

def bersihkan_teks(teks):
    """Hilangkan tanda baca dan spasi berlebih"""
    teks = teks.replace("\n", " ")
    teks = teks.translate(str.maketrans('', '', string.punctuation))
    teks = re.sub(r'\s+', ' ', teks).strip()
    return teks

def kata_list(teks):
    """Pisahkan teks menjadi token kata"""
    return re.findall(r"[A-Za-zÀ-ÿ]+|\d+", teks)

# -------------------------
# Deteksi jenis pembayaran
# -------------------------

def deteksi_semua_kata(teks, daftar_kata):
    tokens = kata_list(teks.lower())
    hasil = []
    for i, t in enumerate(tokens):
        cocok = difflib.get_close_matches(t, daftar_kata, n=1, cutoff=0.78)
        if cocok:
            hasil.append((i, cocok[0]))
    return hasil, tokens

# -------------------------
# Ekstraksi nama santri
# -------------------------

def extract_name_from_window(tokens, idx):
    """Ambil nama santri di sekitar posisi kata kunci, mencari 1–3 kata."""
    n = len(tokens)

    TRIGGER = {
        "an", "an.", "a.n", "a/n", "atas", "atasnama", "atas_nama",
        "ananda", "untuk", "nama", "santri", "santriwati"
    }

    def is_name_token(tok):
        return tok.isalpha() and tok.lower() not in STOPWORDS and len(tok) > 1

    def get_name_sequence(start_idx, max_words=3):
        name_parts = []
        for i in range(start_idx, min(start_idx + max_words, n)):
            if is_name_token(tokens[i]):
                name_parts.append(tokens[i].capitalize())
            else:
                break
        return " ".join(name_parts) if name_parts else None

    # 1. Coba ambil nama 1–2 kata setelah kata kunci pembayaran
    name = get_name_sequence(idx + 1, max_words=2)
    if name:
        return name

    # 2. Cek trigger words (SOLUSI 3)
    #    Jika ditemukan, ambil 1–3 kata setelahnya
    for j in range(max(0, idx - 5), min(n, idx + 10)):
        if tokens[j].lower() in TRIGGER:
            name = get_name_sequence(j + 1, max_words=3)
            if name:
                return name

    # 3. Fallback ambil kandidat nama di kanan keyword
    for j in range(idx + 1, min(n, idx + 6)):
        name = get_name_sequence(j, max_words=2)
        if name:
            return name

    return "-"

# -------------------------
# Ekstraksi nominal
# -------------------------

def ekstrak_nominal_dari_window(window_text):
    teks_bersih = window_text.replace(".", "").replace(",", "")
    m = re.search(r"(\d{3,}|\d+)\s*(ribu|rb|k)?", teks_bersih, re.IGNORECASE)
    if m:
        angka = m.group(1)
        try:
            return int(angka)
        except:
            return angka
    return "-"

# -------------------------
# Analisis pesan utama (Modified for Streamlit)
# -------------------------

def analisis_pesan(teks_input, keterangan_bulan):
    teks_clean = bersihkan_teks(teks_input)
    lower_clean = teks_clean.lower()

    # Diperbarui: Hapus 'uang' sebagai kata kunci tunggal untuk menghindari deteksi ganda atau salah
    daftar_kata_kunci = ["spp","spb","sppu","sppp", "uang saku", "uang sako","uang spp", "saku", "sako"]
    detected, tokens = deteksi_semua_kata(lower_clean, daftar_kata_kunci)

    hasil = []
    tahun = datetime.now().year

    for idx, found in detected:
        start = max(0, idx-5)
        end = min(len(tokens), idx+7)
        window_tokens = tokens[start:end]
        window_text = " ".join(window_tokens)

        # Tentukan jenis pembayaran
        # Menggunakan 'found' untuk menentukan jenis, jika 'found' adalah 'uang saku' dll, akan jadi Uang Saku
        jenis = "SPP" if "spp" in found or "spb" in found or "sppu" in found or "sppp" in found else "Uang Saku"
        nama = extract_name_from_window(tokens, idx)
        nominal = ekstrak_nominal_dari_window(window_text)

        # ✅ Gabungkan jadi satu kolom dengan nama santri
        keterangan = f"{jenis} {keterangan_bulan} - {tahun} {nama}".strip()

        hasil.append({
            "Tanggal": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Keterangan Pembayaran": keterangan,
            "Nominal": nominal,
            "Potongan Pesan": window_text
        })

    return hasil

def to_excel(df):
    """
    Konversi DataFrame ke format Excel dalam memori (BytesIO)
    untuk diunduh di Streamlit.
    """
    output = io.BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    df.to_excel(writer, index=False, sheet_name='Sheet1')
    writer.close()
    processed_data = output.getvalue()
    return processed_data

# ------------------------- Streamlit App ------------------------- #

streamlit.set_page_config(page_title="AI Pondok - Deteksi Pembayaran", layout="centered")

streamlit.title("🤖 AI Pondok – Deteksi Pembayaran Otomatis")

streamlit.markdown(
    """
    Selamat datang di aplikasi AI Pondok! Aplikasi ini membantu Anda mengidentifikasi
    jenis pembayaran (SPP/Uang Saku), nama santri, dan nominal dari pesan teks.

    Cukup masukkan pesan dari orang tua dan keterangan bulan, lalu klik 'Analisis Pesan'.
    """
)

# Input area for user message
teks_input = streamlit.text_area(
    "Masukkan teks pesan dari orang tua:",
    height=150
)

# Input field for 'keterangan bulan'
keterangan_bulan = streamlit.text_input(
    "Masukkan keterangan bulan pembayaran (contoh: Januari, Februari):"
)

if streamlit.button("Analisis Pesan"):
    if teks_input and keterangan_bulan:
        # Panggil fungsi analisis_pesan yang sudah dimodifikasi
        hasil_analisis = analisis_pesan(teks_input, keterangan_bulan)

        if hasil_analisis:
            df_hasil = pd.DataFrame(hasil_analisis)
            streamlit.success("✅ Pembayaran terdeteksi:")
            streamlit.dataframe(df_hasil)

            # Download button
            streamlit.download_button(
                label="Unduh Data ke Excel",
                data=to_excel(df_hasil),
                file_name=f"hasil_analisis_pembayaran_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        else:
            streamlit.warning("⚠️ Tidak ditemukan pembayaran dalam teks.")
    else:
        streamlit.error("Mohon masukkan teks pesan dan keterangan bulan untuk analisis.")

print("Complete Streamlit application script generated.")

#!pip install --force-reinstall xlsxwriter

#pip install xlsxwriter

pilihan = streamlit.text_input("Pilihan: ")
if pilihan == "1":
        streamlit.write("ketikan no baris")
        streamlit.dataframe(df[["Keterangan Pembayaran"]])  # tampil kolom penting saja

        while True:
          try:
                row_id = streamlit.text_input("\nMasukkan nomor baris (atau ENTER untuk selesai): ")

                if row_id.strip() == "":
                    print("\n✔ Edit selesai.")
                    break
                    row_id = int(row_id)

                if row_id < 0 or row_id >= len(df):
                    print("⚠️ Nomor baris tidak valid.")
                    continue

                nama_baru = streamlit.text_input("Masukkan nama santri baru: ").strip().title()

                # Ambil nilai lama
                keterangan_lama = df.loc[row_id, "Keterangan Pembayaran"]

                # Perbaiki nama dalam string keterangan
                bagian = keterangan_lama.split(" ")
                # Format: SPP Januari - 2025 Ahmad Hakim
                # Nama berada setelah 3 token pertama
                bagian = bagian[:4] + [nama_baru]

                df.loc[row_id, "Keterangan Pembayaran"] = " ".join(bagian)

                streamlit.success("✔ Nama berhasil diperbarui!\n")
                streamlit.dataframe(df)
                streamlit.succes("✔ Edit selesai.")
          except Exception as e:
                streamlit.error(f"⚠️ Error: {e}")